### PR TITLE
Changed Selectors backgrounds to paper in war mode

### PR DESCRIPTION
**Pull request by MrRar**

### CODE REVIEW

**Comment by croxxx** [comment]
For legal reasons I have to ask where these images come from.
Could you please provide a source?

**Comment by MrRar** [comment]
There images are based on pictures that I took of legal paper and then I edited them in gimp.

**Comment by croxxx** [comment]
While I agree replacing the placeholder team and class selection images I think the block textures are better suited as a custom texture pack.

**Comment by MrRar** [comment]
>  I think the block textures are better suited as a custom texture pack.

I think that the war block textures are rather poorly designed. I believe that mine are more refined, and at the same time, inclusive of the average person’s graphical tastes. However I will change them according to your specification. But if you are convinced that the war block textures are the best ever-then I guess I am out of luck.

**Comment by croxxx** [comment]
Quite the opposite. I think you are right at least for the ammo block.

Your textures are nice but would not fit in very well with the general texture style on other blocks. Just imagine one of your blocks next to a grass or stone block.
There is definitely need for a texture overhaul in some places but for the default textures shipped with the game new textures should blend in with the existing ones IMO.

**Comment by MrRar** [comment]
Here are some new guns. Is the medical kit OK?

**Comment by croxxx** [comment]
Merged original request in 1838a02c7b9b4264303177dfe364d9f1892115e3

---
Your other changes have not been merged as of now.
The main problem I see with weapons is them being barely visible in item selector.
gui_bar

The health pack and ammo box are nice.
In my opinion the current medpack is fine, though (why did you see a need to change it).
box_health

The ammo box will probably make its way in at a later point as it is much better than the current one.
I like the carboard box look of it.
box_ammo

---
**P.S.:**
Could you in future please use separate pull requests for different changes?
Like one for selection backgrounds, one for weapon changes. This would make things easier for me to manage.

**Pull request closed without merging**
