### PR TITLE
Real hand images

### PR DESCRIPTION
**Pull request by MrRar**
I created these pictures by rendering 3D models in Blender. I made sure that all the models that I used did not have a restrictive licence. Even if they did have a restrictive licence, I'm not sure taking a picture of the model would be "using" it.

### CODE REVIEW

**Comment by joshi1999** [comment]
MAybe its to realistic? I mean, its a block building game, isnt it?

**Comment by croxxx** [comment]
I have to agree with @joshi1999 here. But keeping the current placeholders isn't a long-term solution either.
What exact licenses did your source models have, @MrRar? Can you provide links to the sources?

---
Ideally we'd need an item renderer that generates 3D models out of 2D textures.
There were once some rumors about work being done on that by a community member but given the time passed since then I don't think that still applies.

**Comment by MrRar** [comment]
I need to refind the files since I did not save the links, but I will do so. I also have a new batch of gun textures that I will commit later.

**Comment by joshi1999** [comment]
3d renderer? Oh the Monster generator is an ilusion? Whoops :x

**Comment by MrRar** [comment]
grenade
[http://www.blender-models.com/model-downloads/weapons/id/hand-grenade/](url)

pistol
[http://tf3dm.com/3d-model/45-acp-smith-and-wesson-13999.html](url)

rifle
[http://blenderartists.org/forum/showthread.php?196590-Blend-HK-UMP-submachine-gun](url)

shotgun
[http://www.blender-models.com/model-downloads/weapons/id/mossberg-12-guage-shotgun/](url)

submachinegun
[http://tf3dm.com/3d-model/mp5k-fully-rigged-60158.html](url)

**Comment by MrRar** [comment]
Very old.

**Pull request closed without merging**
