### PR TITLE
TerrainChunkTesselator refactored

### PR DESCRIPTION
**Pull request by TobiMob**
I refactored the TreeainChunkTesselator.ci.cs a bit.
It should behave like bevore, except the water, which should look better now.

These changes depend on the newer Cito with float support (also contained in this branch).
I could not find anything broken, but someone else should test it too, bevore it gets pulled.

waterok

### CODE REVIEW

**Comment by TobiMob** [comment]
Meh.
_The command "git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1" exited with 128._

**Comment by croxxx** [comment]
Okay, just tested your changes.
Performance seems good.

Water indeed looks good now. Nice work!
Just one little issue I found there:


Unfortunately shadows are really buggy for me.
Top 2 blocks seem to be fine. Under those things get strange, though.
Some examples:

**Comment by croxxx** [comment]
Little update:
Simple shadows completely screw things up for me.

**Comment by croxxx** [comment]
Found some issues regarding special blocks:
- Cactus sides are not drawn when a solid block is nearby.
    
- Stair top is not drawn when a solid block is above. Also Cactus texture does not "hang over" the edges as before.  
    **Nice to have (missing in current code as well):** *It would be cool if sides of stairs would not be drawn when another stair is next to it. Should increase performance with many stairs and fix border flickering (also seen in image)*

**Comment by TobiMob** [comment]
Hi,  
@croxxx, thanks for taking the time to look over it!
I already fixed the Stairs/Cactus/Fences once, but looks like I broke them again, without noticing (shame on me!).
But I know where to look, that should not be the problem.

What really bugs me are the shadows, not sure how I could missed that. Maybe because the world on my screenshot looks kinda flat...
Not sure what the reason for that is. This may take some time.

Lowered Blocks:
I also thought about the handling for the lowered blocks (stairs/rails).
It could get complicate if a block has a dynamic height, like rails for example.
Maybe a "Slope"-type could be added for these.
I will thinker a little more about this.

I will pull this one back for now and come again, if it is no longer totally broken :)

**Pull request closed without merging**
